AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Config Rule triggered on the change of a RouteTable
Resources:
  s3epConfigRule:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: s3epConfigRule.lambda_handler
      CodeUri: .
